import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Antonia',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Nike shirt',
      slug: 'nike-shirt',
      category: 'Tops',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '2',
      name: 'Adidas shirt',
      slug: 'adidas-shirt',
      category: 'Tops',
      image: '/images/p2.jpg',
      price: 200,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '3',
      name: 'Nike pant',
      slug: 'nike-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 8,
      brand: 'Nike',
      rating: 4,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'Adidas pant',
      slug: 'adidas-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
