const data = {
  products: [
    {
      name: 'Nike shirt',
      slug: 'nike-shirt',
      category: 'Tops',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas shirt',
      slug: 'adidas-shirt',
      category: 'Tops',
      image: '/images/p2.jpg',
      price: 200,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike pant',
      slug: 'nike-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 8,
      brand: 'Nike',
      rating: 4,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      name: 'Adidas pant',
      slug: 'adidas-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
